### ISSUE TITLE
HTTPS access should be available by default

### ISSUE THREAD

**Issue by telnoratti** [IQSS/dataverse-aws#2]
At least with EZID when a DOI is registered, it uses `https://`. We don't setup https by default so these URLs are invalid.

**Comment by pdurbin** [comment]
Yeah, SWORD requires https as well. Well, it always returns https URIs at least: https://github.com/IQSS/dataverse/blob/v4.5/src/main/java/edu/harvard/iq/dataverse/api/datadeposit/UrlManager.java#L185

**Comment by telnoratti** [comment]
There doesn't seem to be an easy way to automate this. I think the best way to do this is to create a certificate manually and upload to amazon ACM, then provide another field for the ARN of the certificate to use. The name on the cert will not match the DNS name on the load balancer, but it will at least have a cert.

For production use a CNAME would be created for the load balancer so the cert could match it.

Alternatively if you were going to use this for testing builds, there might be integration potential with route53 and a wildcard cert. For example, we point NS records for dataverse.vtti.vt.edu at route53, then provision a DNS record as part of the cloudformation template. We also insert a wildcard cert into ACM for *.dataverse.vtti.vt.edu.

Given the complexity involved with the second solution, I'm going to focus on getting the first one working.

**Comment by telnoratti** [comment]
3f245f20d1cfbc35daa0e45d590ab1510f0cf614 has added a field to provide an ARN for an IAM or ACM certificate. If it's filled, HTTPS will be configured on the load balancer.
